
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rpsin
 */
public class Record extends javax.swing.JFrame {

    /**
     * Creates new form Record
     */
    public Record() {
        initComponents();
        try{
        
            
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con = null;
        con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","singhal23");
        PreparedStatement pst = con.prepareStatement ("select * from flight_user");
        ResultSet f = pst.executeQuery();
        if(f.next()){
        t2.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(f));
        }
       }
        catch(ClassNotFoundException | SQLException e){System.out.println(e);
      }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        t2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Phone No", "Address", "Gender", "Age", "Email Id", "Password", "Confirm Password"
            }
        ));
        jScrollPane1.setViewportView(t2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 290, 772, 90);

        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1061, 594, 99, 41);

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 36, 121));
        jLabel1.setText("ARCY TRAVELLERS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(283, 71, 766, 91);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\rpsin\\Desktop\\Flight\\logo1 edit.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 10, 246, 215);

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel3.setText("USERS RECORDS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(531, 242, 212, 30);

        jLabel4.setBackground(new java.awt.Color(196, 223, 251));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1660, 230);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airport-airplanes-gates-flight-line-163771.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-40, -340, 1790, 1480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Admin obj = new  Admin();
                obj.setExtendedState(MAXIMIZED_BOTH);
                obj.setVisible(true);
                this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 Record obj = new  Record();
                obj.setExtendedState(MAXIMIZED_BOTH);
                obj.setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t2;
    // End of variables declaration//GEN-END:variables
}
